server:
  port: ${server.port}
management:
  security:
    flag: false
  server:
    port: ${management.port}
  metrics:
    tags:
      application: '@project.name@'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        url: https://auth.domain
        jwt:
          realm: internal
          issuer-uri: ${spring.security.oauth2.resourceserver.url}/auth/realms/${spring.security.oauth2.resourceserver.jwt.realm}
          resource-id: koffing
info:
  version: '@project.version@'
  stage: dev

wachter:
  auth:
    enabled: true
  serviceHeader: Service
  services:
    ClaimManagement:
      name: ClaimManagement
      url: http://localhost:8097/v1/cm
    DepositManagement:
      name: DepositManagement
      url: http://localhost:8022/v1/deposit
    Domain:
      name: Domain
      url: http://localhost:8022/v1/domain/repository
    DominantCache:
      name: DominantCache
      url: http://localhost:8022/v1/dominant/cache
    FileStorage:
      name: FileStorage
      url: http://localhost:8022/file_storage
    FistfulStatistics:
      name: FistfulStatistics
      url: http://localhost:8022/fistful/stat
    MerchantStatistics:
      name: MerchantStatistics
      url: http://localhost:8022/v3/stat
    Messages:
      name: Messages
      url: http://localhost:8097/v1/messages
    Invoicing:
      name: Invoicing
      url: http://localhost:8097/v1/processing/invoicin
    PartyManagement:
      name: PartyManagement
      url: http://localhost:8097/v1/processing/partymgmt
    PayoutManagement:
      name: PayoutManagement
      url: http://localhost:8097/payout/management
    RepairManagement:
      name: repairManagement
      url: http://localhost:8097/v1/repair
    WalletManagement:
      name: WalletManagement
      url: http://localhost:8022/v1/wallet
    WithdrawalManagement:
      name: WithdrawalManagement
      url: http://localhost:8022/v1/wallet


http-client:
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200

auth.enabled: true
