management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

wachter:
  serviceHeader: Service
  services:
    messages:
      name: messages
      url: http://localhost:8097/v1/messages
    automaton:
      name: automaton
      url: http://localhost:8022/v1/automaton
    repairer:
      name: repairer
      url: http://localhost:8022/v1/repair/withdrawal/session
    claimManagement:
      name: claimManagement
      url: http://localhost:8097/v1/cm
    fistfulAdmin:
      name: fistfulAdmin
      url: http://localhost:8022/v1/admin
    fistfulStatistics:
      name: fistfulStatistics
      url: http://localhost:8022/fistful/stat
    fileStorage:
      name: fileStorage
      url: http://localhost:8022/file_storage
    deanonimus:
      name: deanonimus
      url: http://localhost:8022/deanonimus
    merchantStatistics:
      name: merchantStatistics
      url: http://localhost:8022/stat
    paymentProcessing:
      name: paymentProcessing
      url: http://localhost:8022/v1/processing/invoicing
    domain:
      name: domain
      url: http://localhost:8022/v1/domain/repository


http-client:
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000

orgManager:
  url: http://localhost:8022/org/v1/auth-context
  networkTimeout: 5000

bouncer:
  url: http://localhost:8022/v1/arbiter
  networkTimeout: 10000
  deployment-id: production
  auth-method: SessionToken
  realm: external
  rule-set-id: change_it
  auth:
    enabled: true

keycloak:
  realm: internal
  auth-server-url: http://keycloak:8080/auth/
  resource: koffing
  not-before: 0
  ssl-required: none
  realm-public-key:

auth.enabled: true
