server:
  port: ${server.port}
management:
  security:
    flag: false
  server:
    port: ${management.port}
  metrics:
    tags:
      application: '@project.name@'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        url: https://auth.domain
        jwt:
          realm: internal
          issuer-uri: >
            ${spring.security.oauth2.resourceserver.url}/auth/realms/
            ${spring.security.oauth2.resourceserver.jwt.realm}
info:
  version: '@project.version@'
  stage: dev

woody-http-bridge:
  tracing:
    request-header-mode: WOODY_OR_X_WOODY
    response-header-mode: OFF
    propagate-errors: false
    endpoints:
      - path: /${wachter.endpoint}

wachter:
  endpoint: ${wachter.endpoint}
  auth:
    enabled: true
  serviceHeader: Service
  services:
    Accounter:
      name: Accounter
      url: http://shumway:8022/accounter
    ClaimManagement:
      name: ClaimManagement
      url: http://claim-management:8022/v1/cm
    DepositManagement:
      name: DepositManagement
      url: http://fistful:8022/v1/deposit
    Domain:
      name: Domain
      url: http://dominant:8022/v1/domain/repository
    RepositoryClient:
      name: RepositoryClient
      url: http://dominant:8022/v1/domain/repository_client
    DominantCache:
      name: DominantCache
      url: http://dominant-cache:8022/v1/dominant/cache
    FileStorage:
      name: FileStorage
      url: http://file-storage-v2:8022/file_storage/v2
    FistfulStatistics:
      name: FistfulStatistics
      url: http://fistful-magista:8022/stat
    MerchantStatistics:
      name: MerchantStatistics
      url: http://magista:8022/v3/stat
    Invoicing:
      name: Invoicing
      url: http://hellgate:8022/v1/processing/invoicing
    PartyManagement:
      name: PartyManagement
      url: http://party-management:8022/v1/processing/partymgmt
    PayoutManagement:
      name: PayoutManagement
      url: http://payout-manager:8022/payout/management
    RepairManagement:
      name: repairManagement
      url: http://repairer:8022/v1/repair
    WalletManagement:
      name: WalletManagement
      url: http://fistful:8022/v1/wallet
    WithdrawalManagement:
      name: WithdrawalManagement
      url: http://fistful:8022/v1/withdrawal
    Automaton:
      name: Automaton
      url: http://machinegun-ha:8022/v1/automaton
    Repairer:
      name: Repairer
      url: http://repairer:8022/v1/repair/withdrawal/session
    FistfulAdmin:
      name: FistfulAdmin
      url: http://fistful:8022/v1/admin
    Deanonimus:
      name: Deanonimus
      url: http://deanonimus:8022/deanonimus
    PaymentProcessing:
      name: PaymentProcessing
      url: http://hellgate:8022/v1/processing/invoicing
    IdentityManagement:
      name: IdentityManagement
      url: http://fistful:8022/v1/identity
    Scrooge:
      name: Scrooge
      url: http://scrooge:8022/terminal/balance
    Dominator:
      name: Dominator
      url: http://dominator:8022/v1/dominator
    DMT:
      name: DMT
      url: http://dmt.default:8022/v1/domain/repository
    DMTAuthor:
      name: DMTAuthor
      url: http://dmt.default:8022/v1/domain/author
    DMTClient:
      name: DMTClient
      url: http://dmt.default:8022/v1/domain/repository_client


http-client:
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200

auth.enabled: true

otel:
  resource: http://localhost:4318/v1/traces
  timeout: 60000
  enabled: true

http:
  requestTimeout: 60000
  poolTimeout: 10000
  connectionTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200
